<a href="https://www.kaggle.com/chandrashekarchakali/decision-tree-intuition?scriptVersionId=87116478" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

**Introduction:**

In general a decision tree makes a statement and then makes a decision based on whether or not the statement is true or false. Decision Tree is a supervised learning technique that can be used for both regression and classification problems. It is a tree structured classifier, where internal nodes represent the features of a dataset, branches represent the decision rules and each leaf node represents the outcome. In a decision tree there are two nodes, which are the Decision Node and Leaf Node. Decision nodes are used to make any decision and have multiple branches, whereas Leaf nodes are the output of those decisions and not contain any further branches. The decisions or the test are performed on the basis of features of the given dataset.

**Decision Tree terminologies:**

Root Node: Root node is the top node from where the decision tree starts. It represents the entire dataset, which further gets divided into two or more homogeneous sets..

Leaf Node: Leaf nodes are the final output node, and the tree cannot be segregated further after getting a leaf node.

Splitting: It is the process of dividing the decision node/root node into sub-nodes according to the given conditions.

Branch/Sub Tree: A tree formed by splitting the tree.

Pruning: It is the process of removing the unwanted branches from the tree.

Parent/Child node: The root node of the tree is called the parent node, and other nodes are called the child nodes.

**+How does the Decision Tree algorithm Work?**

In a decision tree, for predicting the class of the given dataset, the algorithm starts from the root node of the tree. This algorithm compares the values of root attribute with the record (real dataset) attribute and, based on the comparison, follows the branch and jumps to the next node.

For the next node, the algorithm again compares the attribute value with the other sub-nodes and move further. It continues the process until it reaches the leaf node of the tree. The complete process can be better understood using the below algorithm:

Step-1: Begin the tree with the root node, says S, which contains the complete dataset.

Step-2: Find the best attribute in the dataset using Attribute Selection Measure (ASM).

Step-3: Divide the S into subsets that contains possible values for the best attributes.

Step-4: Generate the decision tree node, which contains the best attribute.

Step-5: Recursively make new decision trees using the subsets of the dataset created in step -3. 
Continue this process until a stage is reached where you cannot further classify the nodes and called the final node as a leaf node.

**Attribute Selection Measures:**

While implementing a Decision tree, the main issue arises that how to select the best attribute for the root node and for sub-nodes. So, to solve such problems there is a technique which is called as Attribute selection measure or ASM. By this measurement, we can easily select the best attribute for the nodes of the tree. There are two popular techniques for ASM, which are:

1.Information Gain

2.Gini Index

**1. Information Gain:**

Information gain is the measurement of changes in entropy after the segmentation of a dataset based on an attribute.

It calculates how much information a feature provides us about a class.

According to the value of information gain, we split the node and build the decision tree.

A decision tree algorithm always tries to maximize the value of information gain, and a node/attribute having the highest information gain is split first. It can be calculated using the below formula:

Information Gain= Entropy(S)- [(Weighted Avg) *Entropy(each feature)  
Entropy: Entropy is a metric to measure the impurity in a given attribute. It specifies randomness in data. Entropy can be calculated as:

Entropy(s)= -P(yes)log2 P(yes)- P(no) log2 P(no)
Where,

S= Total number of samples
P(yes)= probability of yes
P(no)= probability of no

**2. Gini Index:**

Gini index is a measure of impurity or purity used while creating a decision tree in the CART(Classification and Regression Tree) algorithm.

An attribute with the low Gini index should be preferred as compared to the high Gini index.

It only creates binary splits, and the CART algorithm uses the Gini index to create binary splits.

Gini index can be calculated using the below formula:

Gini Index= 1- âˆ‘jPj2

**Pruning: Getting an Optimal Decision tree**

Pruning is a process of deleting the unnecessary nodes from a tree in order to get the optimal decision tree.
A too-large tree increases the risk of overfitting, and a small tree may not capture all the important features of the dataset. Therefore, a technique that decreases the size of the learning tree without reducing accuracy is known as Pruning. There are mainly two types of tree pruning technology used:

1.Cost Complexity Pruning

2.Reduced Error Pruning.

**Advantages of the Decision Tree:**

1.It is simple to understand as it follows the same process which a human follow while making any decision in real-life.

2.It can be very useful for solving decision-related problems.

3.It helps to think about all the possible outcomes for a problem.

4.There is less requirement of data cleaning compared to other algorithms.

**Disadvantages of the Decision Tree:**

1.The decision tree contains lots of layers, which makes it complex.

2.It may have an overfitting issue, which can be resolved using the Random Forest algorithm.

3.For more class labels, the computational complexity of the decision tree may increase

**Python Implementation of Decision Tree**

In [52]:
# Load the required libraries
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import SVG
from IPython.display import display
from graphviz import Source
import seaborn
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier, export_graphviz,DecisionTreeRegressor
from sklearn.metrics import accuracy_score, recall_score, precision_score,confusion_matrix,mean_absolute_error,mean_squared_error,classification_report

In [53]:
import os
data = pd.read_csv("../input/decision-tree/Data.csv")

In [54]:
data.shape

(5000, 14)

In [55]:
data.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,No,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,No,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,No,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,No,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,No,0,0,0,1

In [56]:
data.describe(include='all')

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000,5000.000000,5000.00000,5000.000000,5000.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4520,NaN,NaN,NaN,NaN
mean,2500.500000,45.338400,20.104600,73.774200,93152.503000,2.396400,1.937938,1.881000,56.498800,NaN,0.104400,0.06040,0.596800,0.294000
std,1443.520003,11.463166,11.467954,46.033729,2121.852197,1.147663,1.747659,0.839869,101.713802,NaN,0.305809,0.23825,0.490589,0.455637
min,1.000000,23.000000,-3.000000,8.000000,9307.000000,1.000000,0.000000,1.000000,0.000000,NaN,0.000000,0.00000,0.000000,0.000000
25%,1250.750000,35.000000,10.000000,39.000000,91911.000000,1.000000,0.700000,1.000000,0.000000,NaN,0.000000,0.00000,0.000000,0.000000
50%,2500.500000,45.000000,20.000000,64.000000,93437.000000,2.000000,1.500000,2.000000,0.000000,NaN,0.000000,0.00000,1.000000,0.000000
75%,3750.250000,55.000000,30.000000,98.000000,94608.000000,3.000000,2.500000,3.000000,101.000000,NaN,0.000000,0.00000,1.000000,1.000000
max,5000.000000,67.000000,43.000000,224.000000,96651.000000,4.000000,10.000000,3.000000,635.000000,NaN,1.000000,1.00000,1.000000,1.000000

In [57]:
def understand_data(data) :
    return(pd.DataFrame({"Datatype":data.dtypes,
                         "No of NAs":data.isna().sum(),
                         "No of Levels":data.apply(lambda x: x.nunique(),axis=0),
                         "Levels":data.apply(lambda x: str(x.unique()),axis=0)}))

In [58]:
# Understanding the given data
understand_data(data)

,Datatype,No of NAs,No of Levels,Levels
ID,int64,0,5000,[ 1 2 3 ... 4998 4999 5000]
Age,int64,0,45,[25 45 39 35 37 53 50 34 65 29 48 59 67 60 38 ...
Experience,int64,0,47,[ 1 19 15 9 8 13 27 24 10 39 5 23 32 41 30 ...
Income,int64,0,162,[ 49 34 11 100 45 29 72 22 81 180 105 1...
ZIP Code,int64,0,467,[91107 90089 94720 94112 91330 92121 91711 939...
Family,int64,0,4,[4 3 1 2]
CCAvg,float64,0,108,[ 1.6 1.5 1. 2.7 0.4 0.3 0.6 8....
Education,int64,0,3,[1 2 3]
Mortgage,int64,0,347,[ 0 155 104 134 111 260 163 159 97 122 193 1...
Personal Loan,object,0,2,['No' 'Yes']
Securities Account,int64,0,2,[1 0]
CD Account,int64,0,2,[0 1]
Online,int64,0,2,[0 1]
CreditCard,int64,0,2,[0 1]

**Observations**

    1. ID and ZipCode are interpreted as int64 
    2. Family, Education, Securities Account, CD Account, Online and CreditCard are all categorical but are interpreted as int64. 
    3. Personal Loan (target column) should be converted from object to categorical.

**Convert all the attributes to appropriate type**

Data type conversion

Using astype('category') to convert the data types

In [59]:
cols = ["Family", "Education", "Personal Loan", "Securities Account", "CD Account", "Online", "CreditCard"]
for col in cols:
    data[col] = data[col].astype('category')

In [60]:
data.dtypes

ID                       int64
Age                      int64
Experience               int64
Income                   int64
ZIP Code                 int64
Family                category
CCAvg                  float64
Education             category
Mortgage                 int64
Personal Loan         category
Securities Account    category
CD Account            category
Online                category
CreditCard            category
dtype: object

Dropping the attributes that are not required - ID and ZipCode

In [61]:
Data = data.drop(["ID","ZIP Code"], axis=1, inplace = False)
Data.columns

Index(['Age', 'Experience', 'Income', 'Family', 'CCAvg', 'Education',
       'Mortgage', 'Personal Loan', 'Securities Account', 'CD Account',
       'Online', 'CreditCard'],
      dtype='object')

Missing Data
Lets check if there are any missing values in the data

In [62]:
Data.isnull().sum()

Age                   0
Experience            0
Income                0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [63]:
cols = ["Family", "Education","Securities Account", "CD Account", "Online", "CreditCard"]
Data = pd.get_dummies(columns = cols, data = Data, drop_first = True)

In [64]:
Data.head(3)

,Age,Experience,Income,CCAvg,Mortgage,Personal Loan,Family_2,Family_3,Family_4,Education_2,Education_3,Securities Account_1,CD Account_1,Online_1,CreditCard_1
0,25,1,49,1.6,0,No,0,0,1,0,0,1,0,0,0
1,45,19,34,1.5,0,No,0,1,0,0,0,1,0,0,0
2,39,15,11,1.0,0,No,0,0,0,0,0,0,0,0,0

In [65]:
cols = Data.columns[Data.columns != 'Personal Loan']
cols

Index(['Age', 'Experience', 'Income', 'CCAvg', 'Mortgage', 'Family_2',
       'Family_3', 'Family_4', 'Education_2', 'Education_3',
       'Securities Account_1', 'CD Account_1', 'Online_1', 'CreditCard_1'],
      dtype='object')

In [66]:
# Performing train test split on the data
X, y = Data.loc[:,Data.columns!='Personal Loan'], Data.loc[:,'Personal Loan']
y = pd.DataFrame(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3,stratify=y,random_state = 123)

In [67]:
clf = DecisionTreeClassifier(max_depth = 2)
clf = clf.fit(X_train, y_train)

In [68]:
clf.feature_importances_

array([0.        , 0.        , 0.67040467, 0.03490606, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.29468927,
       0.        , 0.        , 0.        , 0.        ])

In [69]:
importances = clf.feature_importances_
indices = np.argsort(importances)[::-1]
names = np.asarray(X.columns[indices])
Important = pd.DataFrame(np.sort(importances)[::-1], index = names, columns = ['Imp'])
Important

                           Imp
Income                0.670405
Education_3           0.294689
CCAvg                 0.034906
CreditCard_1          0.000000
Online_1              0.000000
CD Account_1          0.000000
Securities Account_1  0.000000
Education_2           0.000000
Family_4              0.000000
Family_3              0.000000
Family_2              0.000000
Mortgage              0.000000
Experience            0.000000
Age                   0.000000

In [70]:
# Getting the predictions on train and test
train_pred = clf.predict(X_train)
test_pred = clf.predict(X_test)

In [71]:
confusion_matrix_test = confusion_matrix(y_test, test_pred)
confusion_matrix_train = confusion_matrix(y_train, train_pred)

print(confusion_matrix_train)
print(confusion_matrix_test)

[[3117   47]
 [ 200  136]]
[[1339   17]
 [  85   59]]

In [72]:
print(classification_report(y_true = y_test, y_pred = test_pred))

              precision    recall  f1-score   support

          No       0.94      0.99      0.96      1356
         Yes       0.78      0.41      0.54       144

    accuracy                           0.93      1500
   macro avg       0.86      0.70      0.75      1500
weighted avg       0.92      0.93      0.92      1500

In [73]:
clf = DecisionTreeClassifier(max_depth = 4)
clf = clf.fit(X_train, y_train)

In [74]:
train_pred = clf.predict(X_train)
test_pred = clf.predict(X_test)

In [75]:
print(classification_report(y_true = y_train, y_pred = train_pred))

              precision    recall  f1-score   support

          No       0.98      1.00      0.99      3164
         Yes       0.95      0.79      0.87       336

    accuracy                           0.98      3500
   macro avg       0.97      0.90      0.93      3500
weighted avg       0.98      0.98      0.98      3500

In [76]:
print(classification_report(y_true = y_test, y_pred = test_pred))

              precision    recall  f1-score   support

          No       0.98      1.00      0.99      1356
         Yes       0.95      0.81      0.88       144

    accuracy                           0.98      1500
   macro avg       0.97      0.90      0.93      1500
weighted avg       0.98      0.98      0.98      1500

Observe that there is an improvement in the predictions ater using max depth

In [77]:
param_grid = {"criterion": ["gini", "entropy"],
              "min_samples_split": [2, 10, 20],
              "max_depth": [None, 2, 5, 10],
              "min_samples_leaf": [1, 5, 10],
              "max_leaf_nodes": [None, 5, 10, 20],
              }

In [78]:
dt = DecisionTreeClassifier()
clf = GridSearchCV(dt, param_grid, cv = 10)
clf.fit(X_train, y_train)

GridSearchCV(cv=10, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 2, 5, 10],
                         'max_leaf_nodes': [None, 5, 10, 20],
                         'min_samples_leaf': [1, 5, 10],
                         'min_samples_split': [2, 10, 20]})

In [79]:
train_pred = clf.predict(X_train)
test_pred = clf.predict(X_test)

In [80]:
print(classification_report(y_true = y_test, y_pred = test_pred, digits = 4))

              precision    recall  f1-score   support

          No     0.9905    0.9956    0.9930      1356
         Yes     0.9562    0.9097    0.9324       144

    accuracy                         0.9873      1500
   macro avg     0.9733    0.9526    0.9627      1500
weighted avg     0.9872    0.9873    0.9872      1500